# Generated by Django 5.1.1 on 2024-11-07 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_room_job_alter_message_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Topic',
            new_name='Field',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='topic',
            new_name='field',
        ),
    ]
