# Generated by Django 5.1.1 on 2024-11-11 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
