# Generated by Django 5.1.1 on 2024-12-03 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_userprofile_applied_jobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='applied_jobs',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
