# Generated by Django 5.1.2 on 2024-12-08 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_userprofile_applied_jobs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='applied_jobs',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='applied_jobs',
            field=models.ManyToManyField(blank=True, to='base.job'),
        ),
    ]
