# Generated by Django 5.1.1 on 2024-12-08 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_userprofile_applied_jobs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='applied_jobs',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='job_applied',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
