# Generated by Django 5.1.1 on 2024-12-09 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_userprofile_applied_jobs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='applied_jobs',
        ),
    ]
