# Generated by Django 5.1.1 on 2024-12-04 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_userprofile_is_employee_userprofile_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_type',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_employee',
            field=models.BooleanField(default=True),
        ),
    ]
