# Generated by Django 5.1.1 on 2024-12-04 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_remove_userprofile_user_type_userprofile_is_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_employee',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('employee', 'Employee'), ('business', 'Business'), ('staff', 'Staff')], default='employee', max_length=10),
        ),
    ]
