# Generated by Django 5.1.1 on 2024-12-04 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_remove_userprofile_is_employee_userprofile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('EMPLOYEE', 'Employee'), ('BUSINESS', 'Business')], max_length=10),
        ),
    ]
