# Generated by Django 5.1.1 on 2024-12-08 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_userprofile_applied_jobs'),
        ('base', '0015_alter_userprofile_user_type'),
    ]

    operations = [
    ]
