# Generated by Django 5.1.1 on 2024-12-09 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_merge_20241208_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='applied_jobs',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='applied_jobs',
            field=models.ManyToManyField(blank=True, to='base.job'),
        ),
    ]
