# Generated by Django 5.1.1 on 2024-12-08 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_merge_20241208_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='applied_jobs',
        ),
    ]
