# Generated by Django 5.1.1 on 2024-12-08 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_remove_userprofile_applied_jobs_and_more'),
        ('base', '0017_remove_userprofile_applied_jobs'),
    ]

    operations = [
    ]
