# Generated by Django 5.1.1 on 2024-12-09 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_remove_userprofile_applied_jobs_and_more'),
        ('base', '0018_merge_20241208_1846'),
    ]

    operations = [
    ]
